export const TODO_INPUT_CHANGE = 'TODO_INPUT_CHANGE';
export const TODO_FETCH_ALL = 'TODO_FETCH_ALL';
export const TODO_FETCH_SINGLE = 'TODO_FETCH_SINGLE';
export const TODO_LOADER = 'TODO_LOADER';


export const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE';
export const USER_V_ERROR = 'USER_V_ERROR';
export const USER_STATE = 'USER_STATE';